# Generated by Django 4.1.3 on 2022-12-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entrytype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
