# Generated by Django 4.1.3 on 2022-12-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0004_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=20),
        ),
    ]
